# -*- coding: utf-8 -*-
"""Control Statements.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12H3OvhtfzXKzhfNfvsElQiMj9KFz_9Gq
"""

# in

10 in [10, 20, 30]

ornek_sozluk={"a":12, "b":14, "c":16}

ornek_sozluk.keys()             # sadece anahtar kelimeleri verdiirdik  "keys"

"b" in ornek_sozluk

40 in ornek_sozluk.values()

# !!!   çalıştırmak için . dan sonrakinin () UNUTMA

#IF

sınav_sonucu=20

if sınav_sonucu>50:
  print("başarılısın")
else:
  print("başarısız")

# else de n sonra ":" else ise gereksiz koşul yazma

