# -*- coding: utf-8 -*-
"""Continue, Break, Pass, Parantez.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TE0PPmJifcprFyEZuz3jAobji-I15aSr
"""

numara_listesi=[10, 20, 30, 40, 50, 60]
for num in numara_listesi:
  if num<=40:
    print(num)

# bu döngü 6 defa çalışır, çünkü tek tek kontrol eder

#

for num in numara_listesi:
  print(num)
  if num==40:
    break

# {} --> set ve dict(sözlük) için, düzensiz algılar
# [] --> listeler için
# () --> sonradan değiştirilemez, sabit

#

# continue --> sadece o koşulu çalıştırmaz ve devam eder

for num in numara_listesi:
  if num==40:
    continue
  print(num)

# pass --> es geç bu kodu çalıştırmaz

