# -*- coding: utf-8 -*-
"""Değişkenler.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Q4HADVic1x-EfbfgoZUKo-d543qRTy3v
"""

x=5

x #x i sadece x yazarak atamasınını yazdırabiliyoruz yada print(x) yazarak

print(x)

y=2

sonuc=y*x

sonuc

pi=3.14

type(pi)

#yukarda tipini gösterdi

#bölmede kesirli sayı verir
5/2

