# -*- coding: utf-8 -*-
"""Döngü.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GQHpjV6SXsZI-MLiSB6k_mAh6PM2r1kZ
"""

# for loop, while loop

# for

numara_listesi={10, 20, 30, 40, 50, 60}

print("döngü başladı")
for numara in numara_listesi:
  print(numara*2)
print("döngü bitti")

# for un koşulundan sonra ":" gelmeli ve altındaki print te tabı kullanmalısın

sayı_dizisi=[1,2,3,4,5,6,7,8,9]
yeni_liste=[]
for sayı in sayı_dizisi:
  if sayı%2==0:
    yeni_liste.append(sayı)

yeni_liste

# append yeni eleman eklemek için listeye

isim="samira"

for karakter in isim:
  print(karakter.upper())

# tuple --> ikili değer alma yazdırma

tuple_list=[(1,2,3), (4,5,6), (7,8,9)]
for a,b,c in tuple_list:
  print(c)

# paranteze gerek yok tuple old için

sozluk_ornegi={"a":1, "b":2, "c":3}
for key,value in sozluk_ornegi.items():
  print(value)

# items olmasa sadece keys leri getirir ama items ikili (tuple) olarak getirir

sozluk_ornegi.items()

ornek_set={1,2,3,3,4,5,}

ornek_set

sonuc_listesi=[]
for num in ornek_set:
  sonuc_listesi.append(num*2)
  print(num*2)

#

#

# while

x=0
print("döngü başladı")
while x<10:
  print(x)
  x=x+1
print("döngü bitti")

#

ornek_liste=[1,2,2,2,4,5,6,7,2,4]
while 2 in ornek_liste:
  ornek_liste.remove(2)

ornek_liste

while 4 in ornek_liste:
  ornek_liste.remove(4)
  ornek_liste.append(4)

# remove --> çıkar