# -*- coding: utf-8 -*-
"""Fonksiyonlar.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ICIb_HelE1Z4Yc1gQqkQIH7Qs5dlf4qQ
"""

# fonksiyon oluştururken --> define - def
# sadece fonku çağırıyoruz altındakiler için

def merhaba_fonksiyonlar():
  print("merhaba")
  print("fonksiyonlar")

merhaba_fonksiyonlar()

# unutma ()

# parametr input

isim = "samira-mamysheva"
isim.split("-")             # split - gördüğü yere , koyar
                            # buradaki - parametre oluyor

def merhaba_isim(input_string):         # bu () içi daha önce tanımlı olan değişken olmak zorunda değil
  print("merhaba")
  print(input_string)

merhaba_isim("samira")

merhaba_isim("mamysheva")

#

def toplama(num1, num2):
  print(num1 + num2)

toplama(2, 6)

#

def çiçek(saksı):
  print(saksı)

çiçek("kök")

#

def merhaba_soyisim(soyisim = "samancıoğlu"):
  print("merhaba", soyisim)

merhaba_soyisim()

merhaba_soyisim("samira")

# Eğer kullanıcı bu fonksiyonu çağırırken bir isim vermezse, otomatik olarak 'samancıoğlu' ismini kullan."

#

# RETURN - çıktı vermek

def cikarma(x, y):
  print(x-y)          # geri dönmeyen fonk, sonucu göstermez

cikarma(10, 20)

sonuc = cikarma(10, 20)

sonuc

# bak bir şey çıkmadı sonuc yazınca

# doğrusu |

def cikarma(x, y):
  sonuc = x-y
  print(sonuc)
  return sonuc

sonuc = cikarma(10, 20)     # gene çıkartmayı atamayınca çıkmıyor "sonuc yazınca"

#
isim = "samira"
buyuk_isim = isim.upper()
isim

buyuk_isim

#

def string_harf_ile_basliyor_mu(metin, harf):
  if metin[0] == harf:    # yani metnin ilk harfi ile, den sonraki harf aynı ise
    return True
  else:
    return False

string_harf_ile_basliyor_mu("samira", "s")

#

def string_harf_ile_basliyor_mu(metin, harf):
  if harf in metin:
    return True
  else:
    return False

string_harf_ile_basliyor_mu("samira", "p")

# !!! in (içinde) kelimesi, bir şeyin bir listenin veya metnin içinde olup olmadığını sorgular

#

# ARGS, KWARGS (ARGUMENTS, KEY WORD ARGUMENTS)

# normally

def toplama(a, b, c):
  return a+b+c

toplama(10, 20, 30)

# veya

sayı_listem = [10, 30]
sum(sayı_listem)

# ama istediğimiz kadar sayı toplamak istiyorsak |

def sinirsiz_toplama(*args):      # * onu sınırsız yapar o yüzden mutlaka olmalı
  print(args)

sinirsiz_toplama(10, 20, 30, 40)

# toplamadı o yüzden |

def sinirsiz_toplama(*args):
  return sum(args)

sinirsiz_toplama(10, 40)

#

def kwargs_ornek(**kwargs):  # ** --> sınırsız anahtar eşleşmesi ve sözlük type na çevirme
  print(kwargs)

kwargs_ornek(elma=100, armut=200, muz=300)      # sözlük type oldu

#

