# -*- coding: utf-8 -*-
"""Fonksiyonlar_İleri_İşlemler.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Kcoh6lN6lLODcUhzlqvZYYda99eYJP8A
"""

def uce_bolme(num):
  return num/3

uce_bolme(9)

#

numara_listesi = [9, 12,15,18,21]

sonuc_listesi = []
for num in numara_listesi:
  sonuc_listesi.append(uce_bolme(num))

sonuc_listesi

#

# MAP, FİLTER

#map --> tek satıra indirger

map(uce_bolme, numara_listesi)

list(map(uce_bolme, numara_listesi))    # 1,2 | 1'i alıyor 2 yi uyguluyor

#

def icinden_a_geciyor_mu(string):
  return "A" in string

"b" in "Samira"

icinden_a_geciyor_mu("Samira")

string_listesi = ["Samira", "Mamysheva", "Anatolia", "MIS", "1"]
list(map(icinden_a_geciyor_mu, string_listesi))

#

list(filter(icinden_a_geciyor_mu, string_listesi))

# filter --> ise bir süzgeç görevi görür.

# Mantığı: filter, fonksiyona bakar ve sadece cevabı True olanları yeni listeye alır.

#

#LAMBDA --> anonim fonklar için, tek satırlık kod

numara_listesi = [9,12,15,18,21]

list(map(lambda num : num / 2, numara_listesi))

# yada

def ikiye_böl(num):
  return num / 2

#

numara_listesi = [10, 20, 30, 50, 60]

list(filter(lambda num : num % 6 == 0, numara_listesi))

# yada

yeni_liste = []
for num in numara_listesi:
  if num % 6 == 0:
    yeni_liste.append(num)

yeni_liste

#

# SCOPE --> kapsam

x = 20
def carpma(num):
  x = 5
  return num*5

print(x)

carpma(10)

# sebebi iki x inde kapsamının farklı olması

# LEGB --> Local, Enclosing, Global, Built-in

isim = "Samira"

def ornek_fonksiyon():
  #enclosing
  isim = "Samira 2"
  print(isim)

  def ic_fonksiyon():
    #local
    isim = "Samira 1"
    print(isim)

  ic_fonksiyon()              # iç fonkun çalışması için gerekli o yüzden def ile aynı hizada

ornek_fonksiyon()

# ornek ve ic fonksiyondaki ismi yoruma alırsak çıktı "Samira" olur

# içerden başlar eğer bulamazsa dışarıdakine bakar

# global değişkeni fonkisyonu içinden etkiler

y = 12
def y_degissin():
  global y
  y = 5
  return y * 5

y_degissin()

print(y)

# yani global yokken print(y) 12 ama varsa o zaman içteki y olur