# -*- coding: utf-8 -*-
"""Listeler.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qGHKkIGHJYGs5Yw3n5_8nDy0oFF_C_4K
"""

numara_listesi = [10, 20, 30, 40, 50, 60, 70]

numara_listesi[0]

numara_listesi[-1]

type(numara_listesi)

isim="samira"

isim[0]

isim[0] = "m"     #çalışmaz

numara_listesi[0] = 200           #burda oluyor

numara_listesi

numara_listesi.index(30)

matrix_listesi = [[10,20,30], [40,20,60]]

len(matrix_listesi)

matrix_listesi[0][2]          #yani sıfırıncı indexin 3. elemanı lazım

