# -*- coding: utf-8 -*-
"""OOP.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XE43s55CRfANrzYPSTWZYa2YW0Cqz4EZ
"""

# INHERİTANCE

class Muzisyen:
  def __init__(self, isim, yas):     # init kullandık objenin özel kaydetmek için
    self.isim = isim
    self.yas = yas
    print("Müzisyen sınıfı oluşturuldu")

  def ornek1(self):              # gerek yok inite
    print("örnek 1")

  def ornek2(self):
    print("örnek 2")

beethoven = Muzisyen("Beethoven")

beethoven.ornek1()



class Ozel_Muzisyen(Muzisyen):   # "Muzisyen" in tüm özl lerini aktardık

  def __init__(self, isim, yas):
    Muzisyen.__init__(self, isim, yas)   # Muzisyen den özl geçmesi için gerekli bir kurulum
    print("Özel Müzisyen sınıfı oluşturuldu")

  #override
  def ornek1(self):
    print("örnek 1 çalıştırıldı ama özel müzisyen")

beethoven = Ozel_Muzisyen("Beethoven", 2)



beethoven.ornek2()

beethoven.ornek1()



# POLYMORPHİSM  --> aynı ismi kullanarak farklı işlemler yapma

class Muz:

  def __init__(self, isim):
    self.isim = isim

  def bilgi_ver(self):
    return f"{self.isim} 100 kaloridir"


class Elma:

  def __init__(self, isim):
    self.isim = isim

  def bilgi_ver(self):
    return f"{self.isim} 150 kaloridir"

# print: Televizyon ekranına bir görüntü yansıtmak gibidir; görürsün ama eline alıp başka yere götüremezsin.

# return: Bir fırından ekmek almak gibidir; fırıncı ekmeği sana verir (return), sen o ekmeği ister yersin, ister sandviç yaparsın, ister başkasına verirsin.

muz = Muz("muz")

muz.bilgi_ver()

elma = Elma("elma")

elma.bilgi_ver()

#

meyveler = [muz, elma]

for meyve in meyveler:
  print(meyve.bilgi_ver())



# ENCAPSULATİON  --> değişkenlerin ne zaman değiştirilip değiştirilemeyeceğini kontrol ediyoruz

class Telefon:

  def __init__(self, isim, fiyat):
    self._isim = isim
    self.fiyat = fiyat

  def bilgi_ver(self):
    print(f"{self._isim} in fiyatı: {self.fiyat}")

  def isim_degistir(self, isim):
    self._isim = isim

  def _gizli_metod(self):
    print("gizli method çalıştırıldı")

pixel = Telefon("Pixel XL", 500)

pixel.bilgi_ver()

pixel.isim = "Pixel XLL" # değiştiremedi

pixel.bilgi_ver()

pixel.isim_degistir("Pixel XLL")

pixel.bilgi_ver()

# ._  -->  değişkeni korumak, lütfen dışardan dokunma demek
# _  -->  değişkenin başına koymak lütfen dışardan dokunma demek



# ABSTRACTİON  -->  soyutlamam, soyut sınıf
# diğer sınıflara baz olsun diye

from abc import ABC, abstractclassmethod

class Araba(ABC):

  @abstractclassmethod    # abstract amacı tüm araba markalarının uyması gereken kuralları belirlemek
  def max_hiz(self):      # herkes beygir ve maxı tanımlamak zorunda
    pass                  # pass zorunluluk çünkü bu fonklardan iş yapması beklenmez

  @abstractclassmethod
  def beygir_gucu(self):
    pass

class Ornek():

  def ornek(self):
    pass

ornek = Ornek()

class Mercedes(Araba):

  def __init__(self, isim):
    self.isim = isim

  def beygir_gucu(self):
    return 500

  def max_hiz(self):
    return 100

merc = Mercedes("mercedes c 200")

merc.beygir_gucu()

merc.max_hiz()



# special method or dunder methods --> yerleşik fonklarla(print,len) nasıl etkileşime gireceiğini belirler

class Meyve:

  def __init__(self, isim, kalori):
    self.isim = isim
    self.kalori = kalori

  def __str__(self):
    return f"{self.isim} ın kalorisi şudur: {self.kalori}"

  def __len__(self):
    return self.kalori

portakal = Meyve("portakal", 200)

print(portakal)

len(portakal)

uzum = Meyve("üzüm", 250)

len(uzum)

str(uzum)

