# -*- coding: utf-8 -*-
"""PC2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OQI0mhZ0eTVHUhJkC0TukyEL4A04zJwl
"""

# if ten sonraki satır boşlukla başlamalı

x=8
type(x)

# kullanılamayan değişken isimleri:
2myvar
my var
my-var



x, y,z = "Orange", "Banana", "Cherry"
print(x)
print(y)
print(z)

fruits = ["apple", "banana", "tangeries"]
x, y, z = fruits
print(x)

print(y, z)

print(x+y+z)



x = 5
y = "John"

print(x, y)      # artı değilde virgül kullan yan yana yazmak için

x = "awesome"

def myfunc():
    x = "fantastic"
    print("python is:" + x)

myfunc()                    #bu zorunlu resmen bu fonku çalıştırmak için
print("my func:" + x)



# \n - new line

# x = 5 -> assigment
# x == 5 --> boolean - doğru mu yanlış mı



a = 200
b = 33
if b > a:
  print("b is greater than a")
else:
  print("a is greater than b")



# 33.5 --> // -> 0.5

# ** üssü sayı - 2**3 --> 2 üssü 3

"The sum of {} and "



num1= float(input("enter a number: "))
num2= float(input("enter a number: "))

# equal
if num1==num2:
  print("The numbers are equal")
else:
  print("The numbers are not equal")

# not equal
if num1!=num2:
  print("Numbers are not equal")
else:
  print("Numbers are equal")

# greather than
if num1 > num2:
  print("First number is greater than second number")
else:
  print("First number is not greater than second number")

# less than
if num1 < num2:
  print("First number is less than second number")
else:
  print("First number is not less than second number")

