# -*- coding: utf-8 -*-
"""PC3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EHSibAlQebGhS8b-hP7Xn243JsyCHUuO
"""

# create checks if given temperature is above 25 degrees celcius. if it is "it is warm day" otherwise "it is not warm day"

degree = float(input("Enter degree: "))

if degree >= 25:
  print("It is a warm day")

else:
  print("It is not a warm day")

if "It is a warm day":          # yazıyı if statementte kullanabiliyoruz condition olarak
  print("I love summer")



number = 0

if number > 0:
  print("Positive number")

elif number == 0:               #bu kısım hep unutuluyor
  print("Zero")

else:
  print("Negative number")

print("This statement is always executed")



# program that assigns latter grade based on given numerical grade.

#! eşitlik koymayı unutma

grade = float(input("Enter your letter grade: "))

if grade > 100:
  print("invalid")
elif grade >= 90:
  print("A")
elif grade >= 80:
  print("B")
elif grade >= 70:
  print("C")
elif grade >= 60:
  print("D")
elif grade < 0:
  print("F")
else:
  print("invalid")

#UNUTTUN --> 100 ün üstünde ve 0 ın altında kullanıcı sayı girerse

# yada başa bunu yazarsın EN BAŞA
if grade < 0 or grade > 100:
  print("Valid Grade")



# if person eligible to vote based on their age. if 18 and older, check if their registred

age = float(input("Enter your age: "))

if age >= 18:
  registered = input("Are you registered? Write y/n: ")       # float sayı olarak görür ve hata verir o yüzden sildik, "registered diye yeni değişken tanımladık"

  if registered == "y":
    print("You are eligable for vote")

  elif registered == "n":
    print("You are not eligable for vote")
  else:
    print("Invalid")

else:
  print("You are not eligable for vote")



# take name of a month as input and prints the numbers of days in that month. Assume februrary has 28

month = input("Enter a month: ")

if month == "january" or month =="march" or month =="may" or month =="july" or month =="august" or month =="october" or month =="december":
  print("This month takes 31 days")

elif month == "april" or month =="june" or month =="september" or month =="november":
  print("This month takes 30 days")

elif month == "february":
  print("This month takes 28 days")

else:
  print("valid")

# gene float yazdın yazma
# her birine mont== yazmasakta çalışıyordu



# determine if a fiven year is a leap year. a leap year is divisible by 4 but not by 100 unless it is also divisible by 400

leap_year = int(input("Enter a year: "))

if leap_year % 4 == 0:
  if leap_year % 100 == 0:
    if leap_year % 400 == 0:
      print("leap year")
    else:
      print("not leap year")
  else:
    print("leap year")
else:
  print("not leap year")

#YAPAMADIN

