# -*- coding: utf-8 -*-
"""Range ve Enumerate, Kütüphnae İmport.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wRkzXFKoDtkzZ-OEn6QF4zQFxCHHjnMR
"""

# RANGE --> başlangıç, bitiş ve kaçarlı gideceğini verir, aralık

range(20)

list(range(20))

#

ornek_liste=[1,2,3,4,5,6,7,8]
for num in ornek_liste:
  print(num)

#

# ENUMURATE --> AYNI ANDA HEM İNDEXİ HEM DEĞERİ VERİR

for ix in range(len(ornek_liste)):
  print(ornek_liste[ix],ix)

for element in enumerate(ornek_liste):
  print(element)

# bu tuple unpacking

#

#

# KÜTÜPHANE Kullanma

import math

math.sqrt(64)

from math import cos

cos(90)

#tekini kullanmak için math. kullanmadan her biri için

#

#

# ZİP --> farklı listeleri birbirine bağlamak için

spor_listesi=["yüzme", "koşma", "basketbol"]
kalori_listesi=[100, 150, 200]
gün_listesi=["pzt", "çrş", "prş"]

list(zip(spor_listesi, kalori_listesi, gün_listesi))

#

#

# List Comprehension --> daha temiz tek satırlık kod yazmaktır

örnek_liste=[10,20,30,40,50]
sonuc_liste=[]
for num in örnek_liste:
  if num % 6 == 0:
    print(num)

# -->

sonuc_liste = [num for num in örnek_liste if num % 6 ==0]

sonuc_liste

