# -*- coding: utf-8 -*-
"""Setler.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nBSu8NkMxJJVYESv94EFz9bjj5bqM1g0
"""

# set -> unique & unordered collection of elements  {} ---> olmalı !!!

ornek_liste=[10,10,10,10,20,20,20,30]

ornek_set={10,10,10,10,20,20,20,30}

type(ornek_set)

ornek_set

# yani birden fazla yazılmış elemanları ayırdı ve sıraya soktu

x=3.14

int(x)

#değiştirdik x i

kullanici_yaşı="38"

kullanici_yaşı * 2

int(kullanici_yaşı)*2

# set te index mantığı [0] YOK

birinci_set={10,20,30,40}
ikinci_set={20,30,40,50}

birinci_set.intersection(ikinci_set)

birinci_set.difference(ikinci_set)

