# -*- coding: utf-8 -*-
"""String.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eOIxuHg40UW_FgoaCAtslenLRLbwTT3F
"""

isim="samira"
# ' tek tırnakta olur ama karışabilir kesme işareti kullanınca

type(isim)

isim.capitalize()
#ilk harfi büyütme nokta konulunca fonklar ortaya çıkar
#parantez içi boş olmalı

isim+isim

#fonkların ne işe yaradığını öğrenmek için
help(isim.count)

#() çalıştırma işaretidir

isim.endswith("f")
#yani kontrol ediyoruz sonuncu harfin ğ ile bitip bitmediğini

#İNDEX

isim[0]

isim[5]

len(isim)
#len uzunluk yani karakter sayısını verir

len(isim)+2

isim[len(isim)-10]

isim[-1]
#sonuncudan çıkarır, sondan başlatır

isim[0]

#SLİCİNG   [: :]

barkod ="ABCDE123456"

# [starting_index : stopped_index : step_size]

barkod[2::]     #ilk karakterleri siler

barkod[:5:]     #son karakterleri siler

barkod[::2]

barkod[::-1]
#-1 tersten yazdırır

# isim.index(ş) -> olmadığı için hata veriri
# isim.find("ş") -> hata vermez

isim.split()

isimler="atıl,mehmet"

isimler.split(",")      #farklı elemanlara ayırdı

isimler.split()

