# -*- coding: utf-8 -*-
"""Sözlükler.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MbhXJ8WbD0PSxGvvKumcPVbhptILkrOq
"""

# key-value pairing

spor_listesi = ["koşma", "yüzme", "basketbol"]
kalori_listesi = ["100", "150", "200"]

spor_listesi[1]

seçilen_index=1

print(kalori_listesi[seçilen_index], spor_listesi[seçilen_index])

# f konulur yazı içinde kodu çalıştırmak için !!!   ->   f" {} "  ---> sadece kod olan kısım süslü parantez içine alınır

print(f"şu spor: {spor_listesi[seçilen_index]}, şu kaloriye sahip: {kalori_listesi[seçilen_index]} " )

spor_sözlüğü={"koşma":100, "yüzme":150, "basketbol":200}

spor_sözlüğü=["koşma"]

# .keys kelimeleri   .values sayı değerlerini çıkartır

string_sozluk = {"a":"anahtar", "b": "baget", "c": "ceylan"}

string_sozluk["a"]

