# -*- coding: utf-8 -*-
"""Sınıflar.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15t5M-fz4l7noowZ2Ug0f3lEJKuI8JBiv
"""

kullanici_isim = "samira"
kullanici_yas = 19
kullanici_cinsiyet = "kadın"

# böyle yazmak her kullanıcı için çok zahmetli onun yerine class kullan

class Kullanici:        # büyük harfle oluşturulur
  isim = ""
  yas = 0
  cinsiyet = ""

samira = Kullanici()
atıl = Kullanici()

# artık samira ve atıl bir obje

atıl.cinsiyet           # artık obje. yazıncca seçenekler beiriyor yas/cinsiyet

samira.yas = 19         # atadık sadece samiraya ait

samira.yas

#

class Kullanici:
  isim = ""
  yas = 0
  cinsiyet = ""

  #intializer -> obje oluşturma

  def __init__(self):          # özel fonk
    print("init çağrıldı!!")   # __init__ --> her obje oluştuğunda bu fonk çağrılacak

samira = Kullanici()

atıl = Kullanici()

# self -->


class Kullanici:
  isim = ""
  yas = 0
  cinsiyet = ""

  def __init__(self, isim, yas, cinsiyet):
    self.isim = isim
    self.yas = yas
    self.cinsiyet = cinsiyet

  def ismi_yazdır(self):
    print(self.isim)

atıl = Kullanici("atıl", 50, "erkek")  #__init__ teki istenilen bilgiyi verdik

# self yazmayınca algılamıyor print te
# o class tan bahsettiğimizi anlaması için self şart

atıl.ismi_yazdır()

# SELF --> class içindeki objenin "samira", "atıl" ın kendisidir
# self.isim -> bu objenin kendi ismi demektir

class Kopek():

  def __init__(self, isim, yas = 3):
    self.isim = isim
    self.yas = yas

barley = Kopek("Barley", 7)

barley.yas

