# -*- coding: utf-8 -*-
"""Sınav2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gIhFWsPlxeg82VlX2BB08H5q4yo32ahr
"""

# 1) Aşağıdaki kodun çıktısı ne olacaktır?

x = 5
y = 11
z = 7

x > y or z < x

# 2) Aşağıdaki kodun çıktısı ne olacaktır?

a = 15
b = 20

if a > 10 and b < 30:
    print("A")
elif a > 20 or b == 20:
    print("B")
else:
    print("C")

# 3) Aşağıdaki sözlükte, değerler içinde u harfinin geçip geçmediğini gösteren bir koşul yazınız

my_dictionary = {"a": 100, "b": "atıl", "c": 330, "d": "u"}
for char in my_dictionary:
  if char=="u":
    print("u")
  else:
    print("not")

#YUKARIDAKİ BOŞ İŞ

"u" in my_dictionary.values()

# yada
for char in my_dictionary:
  if char=="u":
    break

print(char)

# 4) Aşağıdaki sözlükte, anahtarlar içinde k harfinin geçip geçmediğini gösteren bir koşul yazınız

my_other_dictionary = {"x": 20, "y": 5, "z": 40, "e": 60}

for char in my_other_dictionary.keys():
  if char=="k":
    print("k")
  else:
    print("not")

# BU DOĞRUSU

"k" in my_other_dictionary.keys()

# 5) Aşağıdaki listedeki sayılardan sadece çift sayı olanları yazdıran bir kod yazınız.

my_numbers = [3, 2, 5, 4, 7, 6, 19, 20, 32, 28, 1111, 23, 44]
for num in my_numbers:
  if num % 2 == 0:
    print(num)

# 6) Aşağıdaki listedeki sayılar bir dairenin yarı çapını vermektedir.
# Tüm dairelerin çevresini içeren başka yeni bir liste oluşturunuz. (İpucu: 2 * pi * r) Pi 3.14 alınabilir.

r_list = [1, 2, 5, 8, 7, 10, 9, 14]

cevvreler = []
pi = 3.14
r_list = [1, 2, 5, 8, 7, 10, 9, 14]

for r in r_list:
    cevvreler.append(2 * pi * r)
    print(cevvreler)

# 7) Aşağıdaki listede isim - yaş eşleşmelerinin bulunduğu yapılar mevcuttur.
# Sadece yaşların olduğu yeni ve ayrı bir liste oluşturunuz.

age_name_list = [("Atıl", 30), ("Ayşe", 20), ("Ahmet", 65), ("Mahmut", 25)]

yaslar = []
for isim, yas in age_name_list:
  print(yas)

# 8) Aşağıdaki isimlerden birini rastgele yazdıran bir kod yazınız

isimler = ["Atıl", "Ahmet", "Mehmet", "Zeynep", "Fatma"]

from random import randint
isimler[randint(0,len(isimler)-1)]

# 9) Aşağıdaki kodun çıktısı ne olacaktır?

number_list = [4, 7, 12, 19, 20, 8, 45, 240]
[num % 2 == 0 for num in number_list]         # if olsaydı en sonda olurdu, t/f vermesinin sebebi boolean control yapıyor olması

