# -*- coding: utf-8 -*-
"""Tuple.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nWzzgJZJ7kHd2jlJlraiCB0wEBUv65k6
"""

# immutability (değiştirilemez)

örnek_tuple= (10,20,30,40)

type(örnek_tuple)

örnek_tuple.count(30)

örnek_tuple[0]

# değiştirilemiyor değerler

# bool true/false yi verir